spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:maindb
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

  liquibase:
    contexts: dev
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  data:
    mongodb:
      database: library
  main:
    allow-bean-definition-overriding: true