spring:
  liquibase:
    enabled: true
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    contexts: dev

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    io.r2dbc: DEBUG