spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: never
      data-locations: data.sql
      schema-locations: schema.sql
  liquibase:
    contexts: dev
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true